---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-sa
  labels:
    app: vote
    environment: sbx1
  annotations:
    # Sharing dev IRSA roles (sandbox shares dev database)
    eks.amazonaws.com/role-arn: arn:aws:iam::792373136340:role/voting01-dev-vote-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: result-sa
  labels:
    app: result
    environment: sbx1
  annotations:
    # Sharing dev IRSA roles (sandbox shares dev database)
    eks.amazonaws.com/role-arn: arn:aws:iam::792373136340:role/voting01-dev-result-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  labels:
    app: worker
    environment: sbx1
  annotations:
    # Sharing dev IRSA roles (sandbox shares dev database)
    eks.amazonaws.com/role-arn: arn:aws:iam::792373136340:role/voting01-dev-worker-irsa
