apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piyush-demo-1-qa
  namespace: argocd
  labels:
    app: piyush-demo-1
    environment: qa
    tenant: opsera
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-ai/enterprise-voting-demo-only
    targetRevision: HEAD
    path: .opsera-piyush-demo-1/k8s/overlays/qa
  destination:
    name: opsera-usw2-np
    namespace: opsera-piyush-demo-1-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
