apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting2-dev

resources:
- ../../base

commonLabels:
  environment: dev

patches:
- path: patch-replicas.yaml
- path: patch-ingress.yaml

images:
- name: PLACEHOLDER_RESULT_IMAGE
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/voting2-dev-result
  newTag: 6cd8e5aca11a1e7027bdfca0154438caad29fd2c
- name: PLACEHOLDER_VOTE_IMAGE
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/voting2-dev-vote
  newTag: 9cdccd4b83497ba6336e8b6c10fc17113ac51cc2
- name: PLACEHOLDER_WORKER_IMAGE
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/voting2-dev-worker
  newTag: 9cdccd4b83497ba6336e8b6c10fc17113ac51cc2
