apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sperivote11-dev

resources:
  - ../../base
  - configmap.yaml
  - serviceaccounts.yaml

commonLabels:
  environment: dev

patches:
  - target:
      kind: Ingress
      name: sperivote11-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vote-sperivote11-dev.agent.opsera.dev
      - op: replace
        path: /spec/rules/1/host
        value: result-sperivote11-dev.agent.opsera.dev
  - target:
      kind: Deployment
      name: vote
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: result
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: PLACEHOLDER_VOTE_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/sperivote11-dev-vote
    newTag: latest
  - name: PLACEHOLDER_RESULT_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/sperivote11-dev-result
    newTag: latest
  - name: PLACEHOLDER_WORKER_IMAGE
    newName: PLACEHOLDER_ECR_REGISTRY/sperivote11-dev-worker
    newTag: latest
