# Environment-specific ServiceAccounts with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote
  annotations:
    eks.amazonaws.com/role-arn: "PLACEHOLDER_VOTE_IRSA_ROLE"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: result
  annotations:
    eks.amazonaws.com/role-arn: "PLACEHOLDER_RESULT_IRSA_ROLE"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  annotations:
    eks.amazonaws.com/role-arn: "PLACEHOLDER_WORKER_IRSA_ROLE"
