---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-sa
  labels:
    app: vote
    environment: mock1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::792373136340:role/voting01-mock1-vote-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: result-sa
  labels:
    app: result
    environment: mock1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::792373136340:role/voting01-mock1-result-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  labels:
    app: worker
    environment: mock1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::792373136340:role/voting01-mock1-worker-irsa
