apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opseravote1-dev

resources:
  - ../../base
  - configmap.yaml
  - serviceaccounts.yaml

commonLabels:
  environment: dev

patches:
  - target:
      kind: Ingress
      name: opseravote1-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vote-opseravote1-dev.agent.opsera.dev
      - op: replace
        path: /spec/rules/1/host
        value: result-opseravote1-dev.agent.opsera.dev
  - target:
      kind: Deployment
      name: vote
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: result
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: PLACEHOLDER_VOTE_IMAGE
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/opseravote1-vote
    newTag: b70cd45-20260209003445
  - name: PLACEHOLDER_RESULT_IMAGE
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/opseravote1-result
    newTag: b70cd45-20260209003445
  - name: PLACEHOLDER_WORKER_IMAGE
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/opseravote1-worker
    newTag: b70cd45-20260209003445
